### ISSUE TITLE
Tracking: [CLI] Improve testing posture | Phase 2

### ISSUE THREAD

**Issue by iliapolo** [aws/aws-cdk-cli#462]
### Overview

As part of the build and release process, we are running a set of CLI integration tests if any of the CLI code has changed.
These tests currently take 50+ min each and are frequently unstable. We are also missing unit tests where we could have them. In general our branches coverage percentages are comparatively low (68% as of 2024-10-29).

> Second Phase of https://github.com/aws/aws-cdk/issues/31929

### Implementation

We are addressing the shortfall through a number of improvements. See issues for details.

### Issue list

- [ ] aws/aws-cdk#32085
- [ ] aws/aws-cdk#32083
- [ ] aws/aws-cdk#31934
- [ ] aws/aws-cdk#32088
- [x] aws/aws-cdk#31933
- [ ] aws/aws-cdk#31932
